version: "3.9"
services:
  mymicroservice: # Backend
    build:
      context: .
      dockerfile: MyMicroservice/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - gif-search

  gif-search: # Frontend
    build:
      context: .
      dockerfile: gif-search/Dockerfile
    ports:
      - "3000:80"
